management:
  endpoints:
    web:
      exposure:
        include: prometheus
server:
  port: 3030

spring:
  application:
    name: temporal-best-practices

  # temporal specific configs
  temporal:
    connection:
      target: 127.0.0.1:7233
   # namespace: default
