spring:
  # temporal specific configs
  temporal:
    workersAutoDiscovery:
      packages: io.temporal

    workers:
      - task-queue: HelloSampleTaskQueue
        capacity:
          max-concurrent-workflow-task-pollers: 100
          max-concurrent-activity-task-pollers: 100
        rate-limits:
          max-worker-activities-per-second: 0
          max-task-queue-activities-per-second: 0
    workflow-cache:
      max-instances: 500
      max-threads: 500
      usingVirtualWorkflowThreads: true
