spring:
  application:
    name: temporal-workshop-spring-boot-integration

  temporal:
    connection:
      target: ${TEMPORAL_ADDRESS:localhost:7233}
    workersAutoDiscovery:
      packages: io.temporal
