management:
  endpoints:
    web:
      exposure:
        include: prometheus

server:
  port: 3030

spring:
  application:
    name: temporal-worker-versioning

  temporal:
    connection:
      target: 127.0.0.1:7233
    workers-auto-discovery:
      packages:
        - io.temporal
    workers:
      - task-queue: HelloSampleTaskQueue

