management:
  endpoints:
    web:
      exposure:
        include: prometheus
server:
  port: 3030

spring:
  application:
    name: temporal-saga-pattern

  temporal:
    connection:
      target: 127.0.0.1:7233
    workers-auto-discovery:
      packages:
        - io.temporal
    workers:
      - task-queue: SagaTaskQueue
        capacity:
          max-concurrent-workflow-task-pollers: 100
          max-concurrent-activity-task-pollers: 100
        rate-limits:
          max-worker-activities-per-second: 0
          max-task-queue-activities-per-second: 0
    workflow-cache:
      max-instances: 500
      max-threads: 500
      usingVirtualWorkflowThreads: true