# spring:
#   temporal:
#     workers:
#       -  task-queue: HelloSampleTaskQueue
#          deployment-properties:
#            deployment-version: ${TEMPORAL_DEPLOYMENT_NAME:hello-workers}.${TEMPORAL_BUILD_ID:2.0}
#            use-versioning: true
#            default-versioning-behaviour: "PINNED"

